import { ThemeProps, SolidPaint, PlainTextStyle, ThemePalettePaint } from '@funii-inc/funii-assist-types';
export declare const whitePaint: SolidPaint;
export declare const blackPaint: SolidPaint;
export declare const primaryPaint: SolidPaint;
export declare const warningPaint: SolidPaint;
export declare const errorPaint: SolidPaint;
export declare const successPaint: SolidPaint;
export declare const textPrimaryPaint: SolidPaint;
export declare const textSecondaryPaint: SolidPaint;
export declare const textDisabledPaint: SolidPaint;
export declare const backgroundPaint: SolidPaint;
export declare const dividerPaint: SolidPaint;
export declare const textPrimaryThemePaint: ThemePalettePaint;
export declare const textSecondaryThemePaint: ThemePalettePaint;
export declare const LIGHT = 300;
export declare const REGULAR = 400;
export declare const MEDIUM = 500;
export declare const BOLD = 700;
export declare const headline1: PlainTextStyle;
export declare const headline2: PlainTextStyle;
export declare const headline3: PlainTextStyle;
export declare const headline4: PlainTextStyle;
export declare const headline5: PlainTextStyle;
export declare const headline6: PlainTextStyle;
export declare const subtitle1: PlainTextStyle;
export declare const subtitle2: PlainTextStyle;
export declare const body1: PlainTextStyle;
export declare const body2: PlainTextStyle;
export declare const button: PlainTextStyle;
export declare const caption: PlainTextStyle;
export declare const overline: PlainTextStyle;
export declare const SPACING_UNIT = 12;
declare const defaultTheme: ThemeProps;
export default defaultTheme;
//# sourceMappingURL=defaultTheme.d.ts.map