name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@funii-inc'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
      - run: yarn build:page
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/dist
