name: Test
on:
  push:
    paths:
      - src/**
      - examples/**
      - package.json
      - yarn.lock
      - webpack.config.json
      - tsconfig.json
      - tsconfig.component.json
      - tsconfig.webpack.json
      - .github/workflows/test.yml

jobs:
  lint:
    name: Check Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [14] # v12も入れたいが時間節約のため抜いている
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@party-opu'
      - name: Restore Npm Cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: Check Lint
        run: yarn lint

  build:
    name: Check Build
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14] # v12も入れたいが時間節約のため抜いている
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@party-opu'
      - name: Restore Npm Cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: Build Component
        run: yarn build:component
      - name: Build Page
        run: yarn build:page
